# Generated by Django 5.0.4 on 2024-05-10 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cadastro.timestampedmodel')),
                ('cliente', models.CharField(blank=True, max_length=15, null=True, verbose_name='Cliente')),
                ('data', models.DateField(verbose_name='Data serviço')),
                ('rec', models.CharField(blank=True, max_length=50, null=True)),
                ('nota', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nota')),
                ('tag', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tag')),
                ('tipo_serv', models.CharField(choices=[('PARADA', 'PARADA'), ('PROJETO', 'PROJETO'), ('NOTA', 'NOTA'), ('PLANO DE PINTURA', 'PLANO DE PINTURA'), ('INTEGRIDADE', 'INTEGRIDADE'), ('MANUTENCAO', 'MANUTENÇÃO')], max_length=20, verbose_name='Tipo serviço')),
                ('setor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Setor')),
                ('corrosividade', models.CharField(choices=[('N/A', 'N/A'), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('C4', 'C4'), ('C5', 'C5'), ('C6', 'C6')], max_length=15)),
                ('fiscal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fiscal')),
                ('inspetor', models.CharField(blank=True, max_length=50, null=True, verbose_name='inspetor')),
                ('tratamento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tratamento')),
                ('tipo_subs', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo do substrato')),
                ('temp_ambiente', models.CharField(blank=True, max_length=20, null=True, verbose_name='Temperatura ambiente')),
                ('ura', models.CharField(blank=True, max_length=20, null=True, verbose_name='Úmidade relativa')),
                ('po', models.CharField(blank=True, max_length=20, null=True, verbose_name='Ponto de Orvalho')),
                ('temp_super', models.CharField(blank=True, max_length=20, null=True, verbose_name='Temperatura da superfície')),
                ('intemperismo', models.CharField(blank=True, max_length=2, null=True, verbose_name='Grau de intemperismo')),
                ('descontaminacao', models.CharField(blank=True, max_length=20, null=True, verbose_name='Descontaminação')),
                ('poeira_tam', models.CharField(blank=True, max_length=10, null=True, verbose_name='Teste de poeira tamanho')),
                ('poeira_quant', models.CharField(blank=True, max_length=10, null=True, verbose_name='Teste de poeira quantidade')),
                ('teor_sais', models.CharField(blank=True, max_length=10, null=True, verbose_name='Teor sais soluveis na superfície')),
                ('ambiente_pintura', models.CharField(blank=True, max_length=30, null=True, verbose_name='Ambiente pintura')),
                ('rugosidade', models.CharField(blank=True, max_length=20, null=True, verbose_name='Rugosidade')),
                ('laudo', models.BooleanField(default=True)),
                ('rnc_n', models.BooleanField(default=False, verbose_name='RNC?')),
                ('obs_inst', models.TextField(blank=True, null=True, verbose_name='Instrumentos de medição')),
                ('obs_final', models.TextField(blank=True, null=True, verbose_name='Observações finais')),
                ('aprovado', models.BooleanField(default=True)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areaa', to='cadastro.area')),
            ],
            options={
                'ordering': ('pk',),
            },
            bases=('cadastro.timestampedmodel',),
        ),
        migrations.CreateModel(
            name='RelatorioArea',
            fields=[
                ('relatorio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='qualidade.relatorio')),
                ('m2', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Metro quadrado')),
                ('calha_utec', models.CharField(choices=[('N/A', 'N/A'), ('SIM', 'SIM'), ('NÃO', 'NÃO')], max_length=5, verbose_name='Todos pontos de contato foram instalados calha tipo Utec?')),
                ('guia_pc', models.CharField(choices=[('N/A', 'N/A'), ('SIM', 'SIM'), ('NÃO', 'NÃO')], max_length=5, verbose_name='Foram pintados os guias e os pontos de contatos da tubulação?')),
                ('fita_protec', models.CharField(choices=[('N/A', 'N/A'), ('SIM', 'SIM'), ('NÃO', 'NÃO')], max_length=5, verbose_name='Aplicado fita de proteção nos pontos com grampos de fixação?')),
                ('trecho_rec', models.CharField(choices=[('N/A', 'N/A'), ('SIM', 'SIM'), ('NÃO', 'NÃO')], max_length=5, verbose_name='Foi pintado todos trechos recomendados da REC?')),
                ('elastomero', models.CharField(choices=[('N/A', 'N/A'), ('SIM', 'SIM'), ('NÃO', 'NÃO')], max_length=5, verbose_name='Foi Aplicado elastômero nos acessórios?')),
                ('volante_caps', models.CharField(choices=[('N/A', 'N/A'), ('SIM', 'SIM'), ('NÃO', 'NÃO')], max_length=5, verbose_name='Foram pintados todos os volantes e caps?')),
            ],
            bases=('qualidade.relatorio',),
        ),
        migrations.CreateModel(
            name='RelatorioJato',
            fields=[
                ('relatorio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='qualidade.relatorio')),
            ],
            bases=('qualidade.relatorio',),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/', verbose_name='foto')),
                ('rip_numero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorio', to='qualidade.relatorio', verbose_name='RIP')),
            ],
            options={
                'verbose_name': 'foto',
                'verbose_name_plural': 'fotos',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='EtapaPintura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tinta', models.CharField(blank=True, max_length=20, null=True)),
                ('lote_a', models.CharField(blank=True, max_length=20, null=True)),
                ('val_a', models.DateField(blank=True, null=True, verbose_name='Validade lote A')),
                ('lote_b', models.CharField(blank=True, max_length=20, null=True)),
                ('val_b', models.DateField(blank=True, null=True, verbose_name='Validade lote B')),
                ('lote_c', models.CharField(blank=True, max_length=20, null=True)),
                ('val_c', models.DateField(blank=True, null=True, verbose_name='Validade lote C')),
                ('cor_munsell', models.CharField(blank=True, max_length=20, null=True)),
                ('temp_amb', models.CharField(blank=True, max_length=20, null=True, verbose_name='Temp. ambiente')),
                ('ura', models.CharField(blank=True, max_length=20, null=True, verbose_name='Úmidade relativa')),
                ('po', models.CharField(blank=True, max_length=20, null=True, verbose_name='Ponto de Orvalho')),
                ('temp_substrato', models.CharField(blank=True, max_length=20, null=True, verbose_name='Temperatura da substrato')),
                ('diluente', models.CharField(blank=True, max_length=15, null=True)),
                ('met_aplic', models.CharField(blank=True, max_length=20, null=True)),
                ('inicio', models.DateTimeField(verbose_name='Inicio')),
                ('termino', models.DateTimeField(verbose_name='Fim')),
                ('inter_repintura', models.CharField(blank=True, max_length=15, null=True)),
                ('epe', models.CharField(blank=True, max_length=20, null=True, verbose_name='Espessura especificada')),
                ('eps', models.CharField(blank=True, max_length=20, null=True, verbose_name='Espessura seca')),
                ('insp_visual', models.BooleanField(default=True)),
                ('aderencia', models.CharField(blank=True, max_length=15, null=True)),
                ('holiday', models.CharField(blank=True, max_length=15, null=True)),
                ('laudo', models.BooleanField(default=True)),
                ('data_insp', models.DateField(verbose_name='Data inspeção')),
                ('pintor', models.CharField(blank=True, max_length=30, null=True, verbose_name='Matrícula Executante')),
                ('rip_n', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='qualidade.relatorio')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
