# Generated by Django 5.0.4 on 2024-05-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualidade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapapintura',
            name='aderencia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='etapapintura',
            name='diluente',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='etapapintura',
            name='holiday',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='etapapintura',
            name='insp_visual',
            field=models.CharField(choices=[('0', 'APROVADO'), ('1', 'REPROVADO')], default=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='etapapintura',
            name='inter_repintura',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='etapapintura',
            name='laudo',
            field=models.CharField(choices=[('0', 'APROVADO'), ('1', 'REPROVADO')], default=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='ambiente_pintura',
            field=models.CharField(blank=True, choices=[('INTERNO', 'INTERNO'), ('EXTERNO', 'EXTERNO')], max_length=30, null=True, verbose_name='Ambiente pintura'),
        ),
    ]
