# Generated by Django 5.0.4 on 2024-05-14 12:23

import qualidade.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualidade', '0002_alter_etapapintura_aderencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='inicio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inicio'),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='termino',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='etapapintura',
            name='data_insp',
            field=models.DateField(blank=True, null=True, verbose_name='Data inspeção'),
        ),
        migrations.AlterField(
            model_name='etapapintura',
            name='inicio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inicio'),
        ),
        migrations.AlterField(
            model_name='etapapintura',
            name='insp_visual',
            field=models.CharField(blank=True, choices=[('0', 'APROVADO'), ('1', 'REPROVADO')], default=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='etapapintura',
            name='termino',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, default='imagens/logo.png', null=True, upload_to=qualidade.models.logo_directory_path, verbose_name='foto'),
        ),
    ]
