# Generated by Django 5.0.4 on 2024-05-15 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '__first__'),
        ('qualidade', '0003_relatorio_inicio_relatorio_termino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areaa', to='cadastro.area'),
        ),
    ]
