# Generated by Django 5.0.4 on 2024-05-10 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Romaneio',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cadastro.timestampedmodel')),
                ('funcionario', models.CharField(blank=True, max_length=255, null=True)),
                ('entrada', models.DateField(verbose_name='Data de Entrada')),
                ('nf', models.CharField(blank=True, max_length=15, null=True, verbose_name='NF')),
                ('documento', models.CharField(blank=True, max_length=20, null=True, verbose_name='documento referência')),
                ('obs', models.CharField(blank=True, max_length=40, null=True, verbose_name='Obs')),
                ('concluido', models.BooleanField(default=False)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.area')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.solicitante')),
            ],
            options={
                'ordering': ('pk',),
            },
            bases=('cadastro.timestampedmodel',),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor', models.CharField(blank=True, max_length=15, null=True)),
                ('material', models.CharField(choices=[('perfil_I', 'perfil_I'), ('perfil_H', 'perfil_H'), ('perfil_U', 'perfil_U'), ('perfil_L', 'perfil_L'), ('barra_chata', 'barra_chata'), ('tubulacao', 'tubulacao'), ('acess_T', 'acess_T'), ('acess_FLG', 'acess_FLG'), ('acess_RED', 'acess_RED'), ('acess_CV90', 'acess_CV90'), ('acess_CV45', 'acess_CV45'), ('acess_VV', 'acess_VV'), ('acess_VVC', 'acess_VVC'), ('acess_CAP', 'acess_CAP'), ('boleado', 'boleado'), ('carretel', 'carretel'), ('cubo', 'cubo'), ('cone', 'cone'), ('janela', 'janela')], max_length=15)),
                ('descricao', models.CharField(blank=True, max_length=30, null=True, verbose_name='Descrição')),
                ('polegada', models.CharField(blank=True, max_length=4, null=True, verbose_name='Pol')),
                ('m_quantidade', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='M/QTD')),
                ('m2', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='M²')),
                ('raio', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='raio')),
                ('largura', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='largura')),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='altura')),
                ('comprimento', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='comprimento/lados')),
                ('lados', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='QTD')),
                ('relatorio', models.CharField(blank=True, max_length=20, null=True)),
                ('jato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemjato', to='cadastro.itembm')),
                ('ta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemta', to='cadastro.itembm')),
                ('tf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemtf', to='cadastro.itembm')),
                ('ti', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemti', to='cadastro.itembm')),
                ('n_romaneio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='romaneios', to='canteirojato.romaneio')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
