# Generated by Django 5.0.4 on 2024-05-15 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '__first__'),
        ('canteirojato', '0002_remove_romaneio_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='jato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itemjato', to='cadastro.itembm'),
        ),
        migrations.AlterField(
            model_name='material',
            name='ta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itemta', to='cadastro.itembm'),
        ),
        migrations.AlterField(
            model_name='material',
            name='tf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itemtf', to='cadastro.itembm'),
        ),
        migrations.AlterField(
            model_name='material',
            name='ti',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itemti', to='cadastro.itembm'),
        ),
        migrations.AlterField(
            model_name='romaneio',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.area'),
        ),
        migrations.AlterField(
            model_name='romaneio',
            name='solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.solicitante'),
        ),
    ]
